
spring:application:
    name: Construction Management
server:
  port: '7788'

domain:
  datasource:
    generate-dll: 'false'
    driver-class: com.mysql.jdbc.Driver;
spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/constructionManagement
    password: Manuchaitu7787
  jpa:
    show_sql: 'true'
    database-platform: org.hibernate.dialect.MySQL8Dialect
  thymeleaf:
    cache: 'false  '
    suffix: '.html '
